apiVersion: apps/v1
kind: Deployment
metadata:
  name: { { .Chart.Name } }
  labels:
    app: { { .Chart.Name } }
spec:
  replicas: { { .Values.replicaCount } }
  selector:
    matchLabels:
      app: { { .Chart.Name } }
  template:
    metadata:
      labels:
        app: { { .Chart.Name } }
    spec:
      containers:
        - name: { { .Chart.Name } }
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 3000
          env:
            - name: DATABASE_HOST
              value: { { .Values.database.host } }
            - name: DATABASE_USER
              value: { { .Values.database.user } }
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: my-app-secret
                  key: password
