apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mysql-credentials
  namespace: external-secrets
spec:
  secretStoreRef:
    name: kubernetes-backend
    kind: SecretStore
  target:
    name: mysql-secret
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: database-credentials
        property: username
    - secretKey: password
      remoteRef:
        key: database-credentials
        property: password
    - secretKey: database
      remoteRef:
        key: database-credentials
        property: database
    - secretKey: rootPassword
      remoteRef:
        key: database-credentials
        property: rootPassword
