apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: kubernetes-backend
  namespace: external-secrets
spec:
  provider:
    kubernetes:
      auth:
        serviceAccount:
          name: default
      server:
        caProvider:
          type: Secret
          name: my-ca-secret
          key: ca.crt
