name: Deploy

on:
  push:
    branches:
      - main
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Branch Name
        run: echo "BRANCH_NAME=$(echo $GITHUB_REF_NAME)" >> $GITHUB_ENV

      - name: Deploy with Helm
        run: |
          chmod +x scripts/deploy.sh
          ./scripts/deploy.sh
